use db_arcana;

START TRANSACTION;

INSERT INTO tb_cartas (nome, numero, palavra_chave, arcano) VALUES
('O Louco', 0, 'novos caminhos, liberdade, impulsividade, aventura', 'maior'),
('O Mago', 1, 'iniciativa, criatividade, manifestação, poder pessoal', 'maior'),
('A Sacerdotisa', 2, 'intuição, mistério, silêncio, sabedoria interior', 'maior'),
('A Imperatriz', 3, 'fertilidade, abundância, cuidado, crescimento', 'maior'),
('O Imperador', 4, 'estrutura, liderança, autoridade, estabilidade', 'maior'),
('O Hierofante', 5, 'tradição, aprendizado, espiritualidade, orientação', 'maior'),
('Os Enamorados', 6, 'escolhas, amor, conexão, dualidade', 'maior'),
('O Carro', 7, 'movimento, conquista, determinação, foco', 'maior'),
('A Justiça', 8, 'equilíbrio, verdade, consequências, racionalidade', 'maior'),
('O Eremita', 9, 'isolamento, reflexão, autoconhecimento, sabedoria', 'maior'),
('A Roda da Fortuna', 10, 'mudanças, destino, ciclos, oportunidades', 'maior'),
('A Força', 11, 'coragem, autocontrole, firmeza emocional', 'maior'),
('O Enforcado', 12, 'pausa, sacrifício, nova visão, espera', 'maior'),
('A Morte', 13, 'transformação, encerramentos, renascimento', 'maior'),
('A Temperança', 14, 'harmonia, paciência, equilíbrio emocional', 'maior'),
('O Diabo', 15, 'apego, tentação, excessos, desejos', 'maior'),
('A Torre', 16, 'ruptura, choque, mudanças inesperadas', 'maior'),
('A Estrela', 17, 'esperança, inspiração, cura, fé', 'maior'),
('A Lua', 18, 'ilusões, insegurança, emoções ocultas', 'maior'),
('O Sol', 19, 'sucesso, felicidade, vitalidade, clareza', 'maior'),
('O Julgamento', 20, 'despertar, renovação, chamado, consciência', 'maior'),
('O Mundo', 21, 'realização, conclusão, plenitude, conquista', 'maior'),
('O Louco', 22, 'novos caminhos, liberdade, impulsividade, aventura', 'maior'),
('Ás de Paus', 1, 'novidade, início, motivação, momento bom para agir', 'menor'),
('Dois de Paus', 2, 'projetos em desenvolvimento, expansão, pensar grande', 'menor'),
('Três de Paus', 3, 'realização de projetos, progresso, planejamento', 'menor'),
('Quatro de Paus', 4, 'celebração, estabilidade, união', 'menor'),
('Cinco de Paus', 5, 'conflitos, disputas, competição', 'menor'),
('Seis de Paus', 6, 'reconhecimento, responsabilidade, vitória', 'menor'),
('Sete de Paus', 7, 'defesa, persistência, coragem', 'menor'),
('Oito de Paus', 8, 'movimento rápido, sucesso, notícias', 'menor'),
('Nove de Paus', 9, 'resistência, cautela, superação', 'menor'),
('Dez de Paus', 10, 'sobrecarga, esforço, responsabilidades', 'menor'),
('Valete de Paus', 11, 'novidades, curiosidade, entusiasmo', 'menor'),
('Cavaleiro de Paus', 12, 'ação, impulsividade, aventura', 'menor'),
('Rainha de Paus', 13, 'autoconfiança, carisma, independência', 'menor'),
('Rei de Paus', 14, 'liderança, ambição, visão', 'menor'),
('Ás de Espadas', 1, 'verdade, revelação, clareza mental', 'menor'),
('Dois de Espadas', 2, 'escolha difícil, reflexão, indecisão', 'menor'),
('Três de Espadas', 3, 'dor, mágoa, decepção, afastamento', 'menor'),
('Quatro de Espadas', 4, 'descanso, pausa, recuperação', 'menor'),
('Cinco de Espadas', 5, 'conflitos, ego, tensão', 'menor'),
('Seis de Espadas', 6, 'deixar ir, avançar, seguir em frente', 'menor'),
('Sete de Espadas', 7, 'segredos, estratégia, cautela', 'menor'),
('Oito de Espadas', 8, 'limitações, medo, bloqueios', 'menor'),
('Nove de Espadas', 9, 'ansiedade, culpa, preocupação', 'menor'),
('Dez de Espadas', 10, 'fim doloroso, encerramento, esgotamento', 'menor'),
('Valete de Espadas', 11, 'curiosidade, vigilância, mensagens', 'menor'),
('Cavaleiro de Espadas', 12, 'mensagem rápida, atitude, intensidade', 'menor'),
('Rainha de Espadas', 13, 'lucidez, sinceridade, independência', 'menor'),
('Rei de Espadas', 14, 'autoridade mental, lógica, estratégia', 'menor'),
('Ás de Copas', 1, 'novo ciclo emocional, amor, novas conexões', 'menor'),
('Dois de Copas', 2, 'harmonia, parceria, fortalecimento de laços', 'menor'),
('Três de Copas', 3, 'celebração, alegria, encontros sociais', 'menor'),
('Quatro de Copas', 4, 'desânimo, introspecção, insatisfação', 'menor'),
('Cinco de Copas', 5, 'tristeza, arrependimento, perdas', 'menor'),
('Seis de Copas', 6, 'nostalgia, passado, memórias', 'menor'),
('Sete de Copas', 7, 'fantasias, escolhas, ilusões', 'menor'),
('Oito de Copas', 8, 'abandono emocional, afastamento, viagem', 'menor'),
('Nove de Copas', 9, 'satisfação, desejos realizados, prazer', 'menor'),
('Dez de Copas', 10, 'felicidade emocional, família, harmonia', 'menor'),
('Valete de Copas', 11, 'sensibilidade, notícias afetivas, criatividade', 'menor'),
('Cavaleiro de Copas', 12, 'mensagens de amor, propostas, emoções', 'menor'),
('Rainha de Copas', 13, 'empatia, intuição, acolhimento', 'menor'),
('Rei de Copas', 14, 'maturidade emocional, equilíbrio, compreensão', 'menor'),
('Ás de Ouros', 1, 'abundância, estabilidade, segurança, solo fértil', 'menor'),
('Dois de Ouros', 2, 'equilíbrio, adaptação, decisões', 'menor'),
('Três de Ouros', 3, 'trabalho em equipe, cooperação, reconhecimento', 'menor'),
('Quatro de Ouros', 4, 'apego, necessidade de segurança, controle', 'menor'),
('Cinco de Ouros', 5, 'dificuldades, insegurança, escassez', 'menor'),
('Seis de Ouros', 6, 'generosidade, trocas, ajuda', 'menor'),
('Sete de Ouros', 7, 'paciência, avaliação, crescimento gradual', 'menor'),
('Oito de Ouros', 8, 'trabalho duro, dedicação, esforço recompensado', 'menor'),
('Nove de Ouros', 9, 'independência, conforto, prosperidade', 'menor'),
('Dez de Ouros', 10, 'estabilidade familiar, legado, abundância', 'menor'),
('Valete de Ouros', 11, 'aprendizado, oportunidades, dedicação', 'menor'),
('Cavaleiro de Ouros', 12, 'constância, responsabilidade, persistência', 'menor'),
('Rainha de Ouros', 13, 'segurança, cuidado, praticidade', 'menor'),
('Rei de Ouros', 14, 'prosperidade, estabilidade, liderança financeira', 'menor');

INSERT INTO tb_arcanos_maiores (id_carta, jornada, arquetipo) VALUES
(1, 0, 'O viajante livre'),
(2, 1, 'O manifestador'),
(3, 2, 'A guardiã da intuição'),
(4, 3, 'A mãe criadora'),
(5, 4, 'O governante'),
(6, 5, 'O mestre espiritual'),
(7, 6, 'A escolha afetiva'),
(8, 7, 'O conquistador'),
(9, 8, 'A juíza'),
(10, 9, 'O sábio interior'),
(11, 10, 'O ciclo do destino'),
(12, 11, 'A coragem compassiva'),
(13, 12, 'O sacrifício consciente'),
(14, 13, 'O transformador'),
(15, 14, 'O mediador'),
(16, 15, 'A sombra e o apego'),
(17, 16, 'A queda das estruturas'),
(18, 17, 'A esperança curadora'),
(19, 18, 'O inconsciente'),
(20, 19, 'A vitalidade'),
(21, 20, 'O chamado do despertar'),
(22, 21, 'A integração final'),
(79, 22, 'O viajante livre');

INSERT INTO tb_arcanos_menores (id_carta, naipe) VALUES
(23, 'Paus'),
(24, 'Paus'),
(25, 'Paus'),
(26, 'Paus'),
(27, 'Paus'),
(28, 'Paus'),
(29, 'Paus'),
(30, 'Paus'),
(31, 'Paus'),
(32, 'Paus'),
(33, 'Paus'),
(34, 'Paus'),
(35, 'Paus'),
(36, 'Paus'),
(37, 'Espadas'),
(38, 'Espadas'),
(39, 'Espadas'),
(40, 'Espadas'),
(41, 'Espadas'),
(42, 'Espadas'),
(43, 'Espadas'),
(44, 'Espadas'),
(45, 'Espadas'),
(46, 'Espadas'),
(47, 'Espadas'),
(48, 'Espadas'),
(49, 'Espadas'),
(50, 'Espadas'),
(51, 'Copas'),
(52, 'Copas'),
(53, 'Copas'),
(54, 'Copas'),
(55, 'Copas'),
(56, 'Copas'),
(57, 'Copas'),
(58, 'Copas'),
(59, 'Copas'),
(60, 'Copas'),
(61, 'Copas'),
(62, 'Copas'),
(63, 'Copas'),
(64, 'Copas'),
(65, 'Ouros'),
(66, 'Ouros'),
(67, 'Ouros'),
(68, 'Ouros'),
(69, 'Ouros'),
(70, 'Ouros'),
(71, 'Ouros'),
(72, 'Ouros'),
(73, 'Ouros'),
(74, 'Ouros'),
(75, 'Ouros'),
(76, 'Ouros'),
(77, 'Ouros'),
(78, 'Ouros');

COMMIT;
